### ISSUE TITLE
Cloudbuild recipe fails to run

### ISSUE THREAD

**Issue by aebrahim** [GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial#1]
It fails with unknown flag: --name

**Comment by ferrarimarco** [comment]
Hi @aebrahim ! Can you share more details about the error you're getting? At which point?

Thanks!

**Comment by aebrahim** [comment]
It's at step 2, using `args: ['buildx', 'create', '--name', 'mybuilder']` that I get `unknown flag: --name`

I suspect those flags are from a previous version of docker and have since been removed. I can reproduce the error locally on my machine with with:

```
~  docker run gcr.io/cloud-builders/docker --version
Docker version 19.03.9, build 9d988398e7
~ docker run gcr.io/cloud-builders/docker buildx create --name mybuilder
unknown flag: --name
See 'docker --help'.

```

**Comment by ferrarimarco** [comment]
This is somewhat surprising because the buildx docs report that flag to be there: https://docs.docker.com/engine/reference/commandline/buildx_create/#name

**Comment by aebrahim** [comment]
I suspect it's related to the version of docker in the cloud build container, and that updating will fix the issue. For example, my locally installed version of docker handles the argument just fine:

```
~ docker --version
Docker version 20.10.13, build a224086
~ docker buildx create --name mybuilder
mybuilder
```

**Comment by ferrarimarco** [comment]
Can you try changing the tag in the cloud-build descriptor from `gcr.io/cloud-builders/docker` (which I think points to `19.03.9` to `gcr.io/cloud-builders/docker:20.10.3` ?

The update to the `latest` tag of the `docker` Cloud Builder is tracked here: https://github.com/GoogleCloudPlatform/cloud-builders/issues/778

Thanks!

My tests:

```shell
$ docker run --rm -it gcr.io/cloud-builders/docker:20.10.3 buildx create --name mybuilder
mybuilder
```

```shell
$ docker run --rm -it gcr.io/cloud-builders/docker buildx create --name mybuilder
unknown flag: --name
See 'docker --help'.
```

```shell
docker run --rm -it gcr.io/cloud-builders/docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:20 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by aebrahim** [comment]
This is so helpful - the docker command is no longer failing!

Do you want me to send you a PR updating the example?

**Comment by ferrarimarco** [comment]
Feel free to! Thanks @aebrahim :)
