### ISSUE TITLE
cloudbuild network not working in arm64 build

### ISSUE THREAD

**Issue by dermasmid** [GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial#10]
when i try to do a multi arch build with the cloudbuild network attached so i can authenticate, the amd64 build works fine and as able to authenticate but the arm64 one is not

**Comment by ferrarimarco** [comment]
Hi @dermasmid! Which error are you seeing in your build logs?

**Comment by dermasmid** [comment]
i am using this package https://www.npmjs.com/package/google-artifactregistry-auth to authenticate with the artifact registry from within the docker build an i'm getting this:
```
 > [linux/arm64  9/19] RUN artifactregistry-auth:
#32 7.261 Retrieving application default credentials...
#32 7.994 Retrieving credentials from gcloud...
#32 8.509 Error: Fail to get credentials. Please run: 
#32 8.509 `gcloud auth application-default login`, `gcloud auth login`, or 
#32 8.509 `export GOOGLE_APPLICATION_CREDENTIALS=<path/to/service/account/key>`
#32 8.509     at Object.getCreds (/usr/local/lib/node_modules/google-artifactregistry-auth/src/auth.js:40:9)
#32 8.509     at async main (/usr/local/lib/node_modules/google-artifactregistry-auth/src/main.js:66:19)
------
Dockerfile:13
```

**Comment by ferrarimarco** [comment]
I'd suggest opening an issue in [their repository](https://github.com/GoogleCloudPlatform/artifact-registry-npm-tools). The [cloud build trigger](https://github.com/GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial/blob/master/terraform/cloud-build/build-docker-image-trigger.yaml) we use doesn't do anything specific to arm64.

Did you try updating the `gcr.io/cloud-builders/docker` builder to the latest version available?
