### ISSUE TITLE
Update this tutorial for CloudBuild Repositories V2 

### ISSUE THREAD

**Issue by lodotek** [GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial#100]
Can this tutorial be updated to support CloudBuild Repositories V2?

Thank you...

**Comment by ferrarimarco** [comment]
Hi @lodotek !

Just to confirm: you mean [this](https://cloud.google.com/build/docs/repositories)?

**Comment by lodotek** [comment]
Yes,
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuildv2_repository

I was able to get it working already, but it might be a good idea to at
least mention on this tutorial that there is a newer version of cloudbuild
available than what is referenced here in the tutorial.
